name: Actions for Unit Testing

on:
    push:
      branches: [ feature* ]
      
    pull_request:
      branches: [ main, dev, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Mocha
      run:
        npm install mocha -g
         npm install --save js-levenshtein
    - name: Unit Testing
      run:
        mocha ./test/square.spec.js
        mocha ./test/greeting.spec.js
        mocha ./test/schedule.spec.js
        mocha ./test/getOffice.spec.js
      env:
        CI: true
